### ISSUE TITLE
Unresolved Reference: ShoppingListItem

### ISSUE THREAD

**Issue by geofflangenderfer** [kotlin-hands-on/jvm-js-fullstack#1]
I get [this](https://imgur.com/a/XtBBiAf) when running the final branch. Am I missing something on importing this class?

**Comment by SebastianAigner** [comment]
Hi @geofflangenderfer! Sorry to hear you're having trouble. My suspicion here is that you are a Kotlin plugin with a 1.4.x-x version. Since no backwards compatibility is guaranteed between the 1.4 and 1.3, the IDE can indeed have resolution errors. You can try opening the project with a 1.3.72 plugin instance, which should work without problems. Let me know if that works for you!

**Comment by SebastianAigner** [comment]
Interpreting your 👍 as "everything is fine" – feel free to open another issue should you run into any more problems!

**Comment by gvbl** [comment]
I installed IntelliJ a few days ago, version:
```
Build #IC-223.8214.52, built on December 20, 2022


Runtime version: 17.0.5+1-b653.23 amd64
```

While following the tutorial I was running into the same problem and updating the plugin instance to 1.3.72 solved it.  Commenting so that someone might update the master template so others won't face the same problem.  Finding this thread via Google search was the only way I would know to fix it.
